name: CI tests, lints and formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Check, Lint, Test, Format, & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain 1.89.0 (w/ tools)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.89.0 
          # Install components needed for linting and formatting
          components: clippy, rustfmt
          
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Cargo fmt (Check)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo build (Debug)
        uses: actions-rs/cargo@v1
        with:
          command: build